###Getting shirts
GET http://localhost:7967/products/
Content-Type: application/json

###Adding a shirt
POST http://localhost:7967/
Content-Type: application/json

{
    "_id": "twoShirts",
    "url": "https://unsplash.com/photos/JskqEILt-ds"
}

###Deleting certain product
DELETE http://localhost:7967/

###
PATCH http://localhost:7967/orders/Anton
Content-Type: application/json

{
    "name":"Anton2"
}
